config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: "tasks#index"

  get '/tasks', to: "tasks#index"

  get '/tasks/new', to: "tasks#new"
  post '/tasks', to: "tasks#create"

  get '/tasks/:id', to: "tasks#show"

  get 'tasks/:id/edit', to: "tasks#edit"
  patch 'tasks/:id', to: "tasks#update", as: 'task'

  delete 'tasks/:id', to: "tasks#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path
  end

  def edit

  end

  def update
    @task.update(task_params)
    redirect_to task_path
  end

  def destroy
    @task.destroy
  end

  private

  def set_task
     @task = Task.find(params[:id])
   end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

<% if !@task.new_record? %>
    <div class="field">
        <%= f.label "Task completed ?" %> <br />
        <%= f.check_box :completed%> <br />
    </div>
<% end %>

</div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task  %>

app/views/tasks/index.html.erb
<h1>Tasks list</h1>

<% @tasks.each do |task| %>
  <% box = task.completed ? '[X]' : '[_]'  %>
  <h2><%=link_to "#{box} #{task.title}", "/tasks/#{task.id}"%></h2>
<% end %>

<%= link_to 'Add a new task', tasks_new_path %>

app/views/tasks/new.html.erb
<%= render 'form', task: @task  %>

app/views/tasks/show.html.erb
<h1>Task</h1>

  <% box = @task.completed ? '[X]' : '[_]'  %>
  <h2><%="#{box} #{@task.title}"%></h2>
  <h3><%= @task.details %></h3>
  <h3><%=link_to "Edit task", "/tasks/#{@task.id}/edit"  %></h3>

  <h3> <%= link_to "Delete", tasks_path,
      method: :delete,
      data: { confirm: "Are you sure?" } %>
  </h3>

  <%= link_to 'Back to list', tasks_path %>